// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EmployeeDeleteRequestTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void employeeDeleteRequest()
    {
        driver.Navigate().GoToUrl("http://localhost:3000/employeeprofile/6");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector("a:nth-child(4) .item-content")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".active .item-content"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        driver.FindElement(By.CssSelector(".active .item-content")).Click();
        driver.FindElement(By.CssSelector("tr:nth-child(1) .btn")).Click();
        Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Request deleted successfully"));
        driver.Close();
        driver.Close();
    }
}
